//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2022-01-31 by the VDM-SL to C++ Code Generator
// (v9.0.5 - Fri 29-Aug-2014 09:17:54 +0900)
//
#ifndef _DefaultMod_anonym_h
#define _DefaultMod_anonym_h


#include "DefaultMod_userdef.h"
#include "metaiv.h"

extern const Quote quote_OPEN_DOOR;

extern const Quote quote_ACTIVATE_ALARM;

class TYPE_DefaultMod_SecSys;
class type_cL;
class type_cLcLM;
class type_cLS;
#define TYPE_DefaultMod_String type_cL

#define TYPE_DefaultMod_Signal Generic

#ifndef TAG_type_cL
#define TAG_type_cL (TAG_DefaultMod + 1)

#endif // TAG_type_cL

#ifndef TAG_type_cLcLM
#define TAG_type_cLcLM (TAG_DefaultMod + 2)

#endif // TAG_type_cLcLM

#ifndef TAG_type_cLS
#define TAG_type_cLS (TAG_DefaultMod + 3)

#endif // TAG_type_cLS

#ifndef TAG_quote_OPEN_DOOR
#define TAG_quote_OPEN_DOOR (TAG_DefaultMod + 4)

#endif // TAG_quote_OPEN_DOOR

#ifndef TAG_quote_ACTIVATE_ALARM
#define TAG_quote_ACTIVATE_ALARM (TAG_DefaultMod + 5)

#endif // TAG_quote_ACTIVATE_ALARM

#ifndef TAG_TYPE_DefaultMod_SecSys
#define TAG_TYPE_DefaultMod_SecSys (TAG_DefaultMod + 6)

#endif // TAG_TYPE_DefaultMod_SecSys

#ifndef DECL_type_cL
#define DECL_type_cL 1


class type_cL : public SEQ<Char> {
public:

  type_cL () : SEQ<Char>() {}


  type_cL (const SEQ<Char> &c) : SEQ<Char>(c) {}


  type_cL (const Common &c) : SEQ<Char>(c) {}


  const wchar_t * GetTypeName () const   {

    return L"type_cL";
  }

}
;
#endif // DECL_type_cL

#ifndef DECL_type_cLcLM
#define DECL_type_cLcLM 1


class type_cLcLM : public MAP<type_cL,type_cL> {
public:

  type_cLcLM () : MAP<type_cL,type_cL>() {}


  type_cLcLM (const MAP<type_cL,type_cL> &c) : MAP<type_cL,type_cL>(c) {}


  type_cLcLM (const Common &c) : MAP<type_cL,type_cL>(c) {}


  const wchar_t * GetTypeName () const   {

    return L"type_cLcLM";
  }

}
;
#endif // DECL_type_cLcLM

#ifndef DECL_type_cLS
#define DECL_type_cLS 1


class type_cLS : public SET<type_cL> {
public:

  type_cLS () : SET<type_cL>() {}


  type_cLS (const SET<type_cL> &c) : SET<type_cL>(c) {}


  type_cLS (const Common &c) : SET<type_cL>(c) {}


  const wchar_t * GetTypeName () const   {

    return L"type_cLS";
  }

}
;
#endif // DECL_type_cLS


#endif // _DefaultMod_anonym_h
