//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2022-01-31 by the VDM-SL to C++ Code Generator
// (v9.0.5 - Fri 29-Aug-2014 09:17:54 +0900)
//


#include "DefaultMod_userdef.h"
#include "metaiv.h"
#include "DefaultMod.h"

#if !DEF_quote_OPEN_DOOR && DECL_quote_OPEN_DOOR
#define DEF_quote_OPEN_DOOR 1

const Quote quote_OPEN_DOOR (L"OPEN_DOOR");

#endif // DEF_quote_OPEN_DOOR

#if !DEF_quote_ACTIVATE_ALARM && DECL_quote_ACTIVATE_ALARM
#define DEF_quote_ACTIVATE_ALARM 1

const Quote quote_ACTIVATE_ALARM (L"ACTIVATE_ALARM");

#endif // DEF_quote_ACTIVATE_ALARM

