//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2022-01-31 by the VDM-SL to C++ Code Generator
// (v9.0.5 - Fri 29-Aug-2014 09:17:54 +0900)
//
#ifndef _DefaultMod_h
#define _DefaultMod_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "DefaultMod_anonym.h"


enum {
  vdm_DefaultMod_SecSys = TAG_TYPE_DefaultMod_SecSys,
  length_DefaultMod_SecSys = 2,
  pos_DefaultMod_SecSys_authorized = 1,
  pos_DefaultMod_SecSys_inside = 2
};

class TYPE_DefaultMod_SecSys : public Record {
public:

  TYPE_DefaultMod_SecSys () : Record(TAG_TYPE_DefaultMod_SecSys, 2) {}

  TYPE_DefaultMod_SecSys &Init (const type_cLcLM &p1, const type_cLS &p2);

  TYPE_DefaultMod_SecSys (const Common &c) : Record(c) {}


  const wchar_t * GetTypeName () const   {

    return L"TYPE_DefaultMod_SecSys";
  }

  type_cLcLM get_authorized () const;
  void set_authorized (const type_cLcLM &p);
  type_cLS get_inside () const;
  void set_inside (const type_cLS &p);
}
;
Bool vdm_DefaultMod_inv_SecSys (const TYPE_DefaultMod_SecSys &);

void init_DefaultMod ();

TYPE_DefaultMod_Signal vdm_DefaultMod_enter (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_String &);

Bool vdm_DefaultMod_pre_enter (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_String &, const TYPE_DefaultMod_SecSys &);

Bool vdm_DefaultMod_post_enter (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_String &, const TYPE_DefaultMod_Signal &, const TYPE_DefaultMod_SecSys &, const TYPE_DefaultMod_SecSys &);

TYPE_DefaultMod_Signal vdm_DefaultMod_leave (const TYPE_DefaultMod_String &);

Bool vdm_DefaultMod_pre_leave (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_SecSys &);

Bool vdm_DefaultMod_post_leave (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_Signal &, const TYPE_DefaultMod_SecSys &, const TYPE_DefaultMod_SecSys &);

void vdm_DefaultMod_addEmployee (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_String &);

Bool vdm_DefaultMod_pre_addEmployee (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_String &, const TYPE_DefaultMod_SecSys &);

Bool vdm_DefaultMod_post_addEmployee (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_String &, const TYPE_DefaultMod_SecSys &, const TYPE_DefaultMod_SecSys &);

void vdm_DefaultMod_removeEmployee (const TYPE_DefaultMod_String &);

Bool vdm_DefaultMod_pre_removeEmployee (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_SecSys &);

Bool vdm_DefaultMod_post_removeEmployee (const TYPE_DefaultMod_String &, const TYPE_DefaultMod_SecSys &, const TYPE_DefaultMod_SecSys &);


#endif // _DefaultMod_h
